100_bottles.alice:pass
ack.alice:pass
array_bounds.alice:pass
bubble_sort.alice:pass
callingSimpleFunction.alice:pass
comparisons.alice:pass
complexFunction.alice:pass
conditional.alice:pass
data_types.alice:pass
doubleFunction.alice:pass
factorial.alice:pass
fibonacci.alice:pass
gcd.alice:pass
hanoi.alice:pass
hello_world.alice:pass
input.alice:pass
looking_glass.alice:pass
looking_glass_array.alice:pass
manytimes.alice:pass
nestedStrangeConditions.alice:pass
primality.alice:pass
quicksort.alice:pass
scope.alice:pass
short_circuit.alice:pass
simpleButNiceLoop.alice:pass
strangecondition.alice:pass
veryLargeLoop.alice:pass
