#!/bin/bash
FILENAME=`basename $1 .alice`
LLVMFILENAME="$FILENAME.ll"
ASSEMBLYFILENAME="$FILENAME.s"

`npm prefix`/node_modules/coffee-script/bin/coffee compileLLVM.coffee $1

if [ -f $LLVMFILENAME ]; then
	/usr/lib/llvm-2.8/bin/llc $LLVMFILENAME

	gcc $ASSEMBLYFILENAME -o $FILENAME
fi