#!/bin/bash
FILENAME=`basename $1 .alice`

~/node_modules/coffee-script/bin/coffee parse.coffee $1 | tee alice.in     

if [ $? -eq 0 ]; then
	./cg <alice.in >alice.ll

	/usr/lib/llvm-2.8/bin/llc alice.ll

	gcc alice.s -o $FILENAME
fi